import os
from PySide6.QtWidgets import QMainWindow, QTableWidgetItem, QListWidgetItem
from PySide6.QtCore import Slot, Qt, Signal
from PySide6.QtGui import QColor

from ui.ui_main_window import Ui_MainWindow

class MainWindow(QMainWindow, Ui_MainWindow):
    """
    Main UI Window for the Meter Test System using compiled UI.
    """
    def __init__(self, device_manager):
        super().__init__()
        self.setupUi(self)  # Sets up the UI generated by pyside6-uic
        self.device_manager = device_manager
        
        self.current_theme = "dark"
        self._load_theme()
        
        self.test_runner = None
        self._populate_devices()
        self._populate_tests()
        
        self._connect_signals()
        
        # Initial state
        self.btn_done.setEnabled(False)
        self.btn_stop.setEnabled(False)
        self.btn_abort.setEnabled(False)
        
    def _connect_signals(self):
        """Wires up UI actions."""
        self.btn_toggle_theme.clicked.connect(self.toggle_theme)
        self.btn_connect_all.clicked.connect(self.device_manager.connect_all)
        self.device_manager.device_status_changed.connect(self.update_device_status)
        
        self.btn_start.clicked.connect(self.start_test)
        self.btn_stop.clicked.connect(self.toggle_pause_resume)
        self.btn_abort.clicked.connect(self.cancel_test)
        self.btn_emergency.clicked.connect(self.trigger_emergency_stop)
        
        # We will dynamically connect btn_done later when needed

    def _load_theme(self):
        """Loads and applies the QSS file based on current theme."""
        theme_file = "dark_theme.qss" if self.current_theme == "dark" else "light_theme.qss"
        theme_path = os.path.join(os.path.dirname(__file__), "resources", "css", theme_file)
        
        try:
            with open(theme_path, "r") as f:
                self.setStyleSheet(f.read())
        except Exception as e:
            print(f"Failed to load theme: {e}")

    @Slot()
    def toggle_theme(self):
        self.current_theme = "light" if self.current_theme == "dark" else "dark"
        self._load_theme()

    def _populate_devices(self):
        """Populates the device table with initial configurations."""
        devices = self.device_manager.get_devices()
        self.table_devices.setColumnCount(4)
        self.table_devices.setHorizontalHeaderLabels(["Name", "Type", "Mock", "Status"])
        self.table_devices.setRowCount(len(devices))
        
        for row, (name, model) in enumerate(devices.items()):
            name_item = QTableWidgetItem(name)
            type_item = QTableWidgetItem(model.type.upper())
            mock_item = QTableWidgetItem("Yes" if model.mock else "No")
            status_item = QTableWidgetItem("Disconnected")
            
            for item in (name_item, type_item, mock_item, status_item):
                item.setTextAlignment(Qt.AlignCenter)
            
            status_item.setForeground(QColor("red") if self.current_theme == "light" else QColor("#f38ba8"))
                
            self.table_devices.setItem(row, 0, name_item)
            self.table_devices.setItem(row, 1, type_item)
            self.table_devices.setItem(row, 2, mock_item)
            self.table_devices.setItem(row, 3, status_item)

    def _populate_tests(self):
        """Populates available test suites."""
        self.list_tests.addItem("G2 Normal Operation Test")
        self.list_tests.setCurrentRow(0)

    @Slot(str, str)
    def append_log(self, level: str, message: str):
        """Appends a new log message to the log panel."""
        color = "#cdd6f4" if self.current_theme == "dark" else "#212529"
        if level == "ERROR":
            color = "#f38ba8" if self.current_theme == "dark" else "#dc3545"
        elif level == "WARNING":
            color = "#f9e2af" if self.current_theme == "dark" else "#ffc107"
            
        html_msg = f'<span style="color:{color};">{message}</span><br>'
        self.txt_logs.insertHtml(html_msg)
        
        scrollbar = self.txt_logs.verticalScrollBar()
        scrollbar.setValue(scrollbar.maximum())

    @Slot()
    def start_test(self):
        """Starts the selected Test."""
        if self.test_runner and self.test_runner.isRunning():
            return
            
        selected_items = self.list_tests.selectedItems()
        if not selected_items:
            self.append_log("WARNING", "No test selected.")
            return
            
        test_name = selected_items[0].text()
        if test_name == "G2 Normal Operation Test":
            from core.test_engine.test_context import TestContext
            from core.test_definitions.g2_normal_operation import G2NormalOperationTest
            from core.test_engine.test_runner import TestRunner
            
            context = TestContext(self.device_manager)
            test_instance = G2NormalOperationTest()
            self.test_runner = TestRunner(test_instance, context)
            
            # Connect signals
            self.test_runner.on_state_changed.connect(self.update_test_state)
            self.test_runner.on_log.connect(self.append_log)
            self.test_runner.on_data_update.connect(self.update_test_data)
            self.test_runner.finished.connect(self.on_test_finished)
            
            # Connect user action signals
            self.test_runner.on_user_action_required.connect(self.prompt_user_action)
            
            # Hardware signals
            hw_service = self.test_runner.context.hardware_service
            if hw_service:
                hw_service.hardware_status_update.connect(self.update_hardware_status)
                hw_service.emergency_triggered.connect(self.on_emergency_triggered)
            
            self.btn_start.setEnabled(False)
            self.btn_stop.setEnabled(True)
            self.btn_abort.setEnabled(True)
            self.btn_stop.setText("Pause")
            
            self.lbl_instruction.setText("Test running...")
            self.progress_bar.setValue(0)
            self.test_runner.start()
        
    @Slot()
    def toggle_pause_resume(self):
        if not self.test_runner:
            return
        from core.test_engine.state_machine import TestState
        current_state = self.test_runner.state_machine.get_state()
        
        if current_state == TestState.RUNNING:
            self.test_runner.pause()
            self.btn_stop.setText("Resume")
            self.lbl_instruction.setText("Test Paused.")
        elif current_state == TestState.PAUSED:
            self.test_runner.resume()
            self.btn_stop.setText("Pause")
            self.lbl_instruction.setText("Test running...")
            
    @Slot()
    def cancel_test(self):
        if self.test_runner:
            self.test_runner.cancel()
            self.btn_abort.setEnabled(False)
            self.lbl_instruction.setText("Aborting...")
            
    @Slot()
    def trigger_emergency_stop(self):
        self.append_log("ERROR", "MANUAL EMERGENCY STOP TRIGGERED!")
        self.lbl_hw_status.setText("HW Status: EMERGENCY STOP")
        self.lbl_hw_status.setStyleSheet("background-color: red; color: white;")
        
        self.btn_start.setEnabled(False)
        self.btn_stop.setEnabled(False)
        self.btn_abort.setEnabled(False)
        self.btn_done.setEnabled(False)
        
        if self.test_runner:
            self.test_runner.cancel()
            hw_service = getattr(self.test_runner.context, 'hardware_service', None)
            if hw_service:
                hw_service.trigger_emergency_stop()

    @Slot(str)
    def update_test_state(self, state_name: str):
        # We can put state in the instruction or live data
        pass
        
    @Slot(dict)
    def update_test_data(self, data: dict):
        voltage = data.get("voltage", "--")
        current = data.get("current", "--")
        pf = data.get("power_factor", "--")
        credit = data.get("credit", "--")
        state = data.get("state", "RUNNING")
        
        self.lbl_live_data.setText(f"State: {state} | V: {voltage}V | I: {current}A | PF: {pf} | Credit: {credit}")
        
    @Slot()
    def on_test_finished(self):
        if "EMERGENCY" not in self.lbl_hw_status.text():
            self.btn_start.setEnabled(True)
            
        self.btn_stop.setEnabled(False)
        self.btn_abort.setEnabled(False)
        self.btn_done.setEnabled(False)
        self.btn_stop.setText("Pause")
        self.lbl_instruction.setText("Test Complete.")
        self.progress_bar.setValue(100)

    @Slot(str, str)
    def update_hardware_status(self, module: str, message: str):
        self.lbl_hw_status.setText(f"HW Status: {module} - {message}")
        if "EMERGENCY" in message or "STOP" in message:
            self.lbl_hw_status.setStyleSheet("background-color: red; color: white;")
        else:
            self.lbl_hw_status.setStyleSheet("")
            
    @Slot()
    def on_emergency_triggered(self):
        self.trigger_emergency_stop()

    @Slot(str, bool)
    def update_device_status(self, device_name: str, is_connected: bool):
        for row in range(self.table_devices.rowCount()):
            item = self.table_devices.item(row, 0)
            if item and item.text() == device_name:
                status_item = self.table_devices.item(row, 3)
                if is_connected:
                    status_item.setText("Connected")
                    color = "#a6e3a1" if self.current_theme == "dark" else "#198754"
                    status_item.setForeground(QColor(color))
                else:
                    status_item.setText("Disconnected")
                    color = "#f38ba8" if self.current_theme == "dark" else "#dc3545"
                    status_item.setForeground(QColor(color))
                break

    # --- User Interaction Protocol ---

    @Slot(str, bool)
    def prompt_user_action(self, message: str, requires_input: bool):
        """Called by the TestRunner when execution pauses for user interaction."""
        self.lbl_instruction.setText(message)
        
        if requires_input:
            self.input_instruction.show()
            self.input_instruction.clear()
            self.input_instruction.setEnabled(True)
        else:
            self.input_instruction.hide()
            
        self.btn_done.setEnabled(True)
        
        # Disconnect any old connections to avoid multiple calls
        try:
            self.btn_done.clicked.disconnect()
        except TypeError:
            pass
            
        self.btn_done.clicked.connect(self.resolve_user_action)

    @Slot()
    def resolve_user_action(self):
        """Called when user clicks 'Done'."""
        self.btn_done.setEnabled(False)
        self.input_instruction.setEnabled(False)
        
        user_val = self.input_instruction.text()
        self.lbl_instruction.setText("Action confirmed. Resuming...")
        
        if self.test_runner:
            self.test_runner.resume_from_user(user_val)

    def closeEvent(self, event):
        self.device_manager.cleanup()
        super().closeEvent(event)
